version: '3'

services:
  mysql:
    image: mysql:8.0.29
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db_alura
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/databasesql/data